apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vde1wtwyc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vde1wtwyc-go 
  name: vde1wtwyc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vde1wtwyc-go 
